spring:
  application:
    name: EduShare QA
    #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/edushare qa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'root'
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 10MB
      #最大请求大小(含所有文件和请求数据 )
      max-request-size: 100MB
#mybatis相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名映射开关
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    bucketName: java-web-siuperap
    region: cn-shanghai